import { buildBanner, buildSupportedTargetLines } from '@laitszkin/tui';
import { formatToolList, buildToolDiscoveryHelp, formatExamples } from '@laitszkin/tool-registry';
import { TARGET_DEFINITIONS, VALID_MODES } from './installer.js';

/**
 * Produces the four help text sections previously generated by standalone
 * functions.  Each method returns text identical to the original builder so
 * that observable CLI output is unchanged.
 */
export class HelpTextBuilder {
  private version: string;
  private colorEnabled: boolean;

  constructor({ version, colorEnabled }: { version: string; colorEnabled: boolean }) {
    this.version = version;
    this.colorEnabled = colorEnabled;
  }

  // ---- shared helpers -------------------------------------------------------

  private modeUsagePattern(): string {
    return `${VALID_MODES.join('|')}|all`;
  }

  private joinLines(lines: (string | undefined | null | false)[]): string {
    return lines.filter(Boolean).join('\n');
  }

  // ---- public methods -------------------------------------------------------

  /** Replaces  buildHelpText  –  top-level overview help. */
  overview(): string {
    const examples = [
      { command: 'apltk --help', result: 'Shows the top-level Apollo Toolkit guide, including install modes and bundled task-tool discovery.' },
      { command: 'apltk tools --help', result: 'Lists bundled tools by task so you can decide which CLI helper to inspect next.' },
      { command: 'apltk architecture --help', result: 'Shows the architecture atlas command tree, task guidance, and action-specific follow-up help paths.' },
      { command: 'apltk tools architecture --help', result: 'Shows what the architecture atlas tool is for, then prints its native command tree and examples.' },
      { command: 'apltk codegraph status --json', result: 'Prints CodeGraph index status in JSON format for programmatic use.' },
    ];

    return this.joinLines([
      buildBanner({ version: this.version, colorEnabled: this.colorEnabled }),
      '',
      'Usage:',
      `  apltk [install] [${this.modeUsagePattern()}]...`,
      `  apollo-toolkit [install] [${this.modeUsagePattern()}]...`,
      `  apltk uninstall [${this.modeUsagePattern()}]... [--yes]`,
      '  apltk tools',
      '  apltk <tool> [...args]',
      '  apltk tools <tool> [...args]',
      '  apltk --help',
      '  apollo-toolkit --help',
      '',
      'Common goals:',
      '  - Install or refresh skills in one or more agent targets: `apltk install --help`',
      '  - Remove manifest-tracked installs from selected targets: `apltk uninstall --help`',
      '  - Discover which bundled helper tool matches a task: `apltk tools --help`',
      '  - Inspect one tool deeply before running it: `apltk tools <tool> --help`',
      '',
      'Bundled tools:',
      formatToolList(),
      '',
      buildToolDiscoveryHelp(),
      '',
      'Options:',
      '  --home <path>  Override Apollo Toolkit home directory',
      '  --symlink      Install skills as symlinks instead of copied directories',
      '  --copy         Install skills as copied directories instead of symlinks',
      '  --yes, -y      Skip uninstall confirmation',
      '  --help         Show this help text',
      '',
      'Examples:',
      formatExamples(examples),
    ]);
  }

  /** Replaces  buildInstallHelpText  –  install-specific help. */
  install(): string {
    const examples = [
      { command: 'apltk', result: 'Launches the interactive installer, opens the target selector, and then walks through link-mode confirmation.' },
      { command: 'apltk codex openclaw --symlink', result: 'Performs a non-interactive install into `codex` and `openclaw` targets using symlinks.' },
      { command: 'npx @laitszkin/apollo-toolkit all --copy', result: 'Installs a copied snapshot into every supported target instead of symlinking.' },
    ];

    return this.joinLines([
      buildBanner({ version: this.version, colorEnabled: this.colorEnabled }),
      '',
      'Usage:',
      `  apltk [install] [${this.modeUsagePattern()}]...`,
      `  apollo-toolkit [install] [${this.modeUsagePattern()}]...`,
      '',
      'Use this when:',
      '  - You want to install or refresh Apollo Toolkit skills in one or more agent targets.',
      '  - You need to choose between symlink mode (auto-updating) and copy mode (stable snapshot).',
      '',
      'Supported targets:',
      buildSupportedTargetLines({ targets: [...TARGET_DEFINITIONS], colorEnabled: this.colorEnabled }),
      '',
      'Behavior notes:',
      '  - Running `apltk` with no targets opens the interactive installer and target selector.',
      '  - `--symlink` keeps installed skills connected to the managed toolkit checkout in `~/.apollo-toolkit`.',
      '  - `--copy` installs a snapshot that only changes when you run the installer again.',
      '  - The installer can optionally include codex-exclusive skills in non-codex targets after prompting.',
      '',
      'Options:',
      '  --home <path>  Override Apollo Toolkit home directory',
      '  --symlink      Install skills as symlinks (recommended)',
      '  --copy         Install skills as copied directories',
      '  --help         Show this install help',
      '',
      'Examples:',
      formatExamples(examples),
    ]);
  }

  /** Replaces  buildUninstallHelpText  –  uninstall-specific help. */
  uninstall(): string {
    const examples = [
      { command: 'apltk uninstall', result: 'Opens the interactive uninstall selector when running in a TTY and then asks for confirmation before removal.' },
      { command: 'apltk uninstall codex agents --yes', result: 'Removes Apollo Toolkit-managed installs from `codex` and `agents` without another confirmation prompt.' },
      { command: 'apltk uninstall codex --home /tmp/custom-home', result: 'Uses the custom managed toolkit home while removing manifest-tracked installs from the selected target.' },
    ];

    return this.joinLines([
      buildBanner({ version: this.version, colorEnabled: this.colorEnabled }),
      '',
      'Usage:',
      `  apltk uninstall [${this.modeUsagePattern()}]... [--yes]`,
      '',
      'Use this when:',
      '  - You want to remove Apollo Toolkit-managed skills from one or more agent targets.',
      '  - You need to clean up manifest-tracked historical installs as well as the current installed skills.',
      '',
      'Supported targets:',
      buildSupportedTargetLines({ targets: [...TARGET_DEFINITIONS], colorEnabled: this.colorEnabled }),
      '',
      'Behavior notes:',
      '  - With no explicit targets, uninstall opens the interactive selector in a TTY and otherwise falls back to all targets.',
      '  - Uninstall removes manifest-tracked current and historical Apollo Toolkit skill directories.',
      '  - `--yes` skips the confirmation prompt after the target list is resolved.',
      '',
      'Options:',
      '  --home <path>  Override Apollo Toolkit home directory',
      '  --yes, -y      Skip uninstall confirmation',
      '  --help         Show this uninstall help',
      '',
      'Examples:',
      formatExamples(examples),
    ]);
  }

  /** Replaces  buildToolsHelp  –  tools listing help screen. */
  toolsHelp(): string {
    const examples = [
      { command: 'apltk tools', result: 'Lists all bundled tools plus the task-oriented discovery guide.' },
      { command: 'apltk tools open-github-issue --help', result: 'Shows when to use the GitHub issue publisher, then prints its exact script flags and examples.' },
      { command: 'apltk tools architecture --help', result: 'Shows when to use the architecture atlas CLI, then prints its native command tree.' },
    ];

    return this.joinLines([
      buildBanner({ version: this.version, colorEnabled: this.colorEnabled }),
      '',
      'Usage:',
      '  apltk tools',
      '  apltk <tool> [...args]',
      '  apltk tools <tool> [...args]',
      '',
      buildToolDiscoveryHelp(),
      '',
      'Bundled tools:',
      formatToolList(),
      '',
      'Tip:',
      '  Pass `--help` after a tool name to view task guidance, native script flags, and concrete examples.',
      '',
      'Examples:',
      formatExamples(examples),
    ]);
  }
}
